### ISSUE TITLE
Cancelling a LocationTask does not cancel the underlying google task

### ISSUE THREAD

**Issue by timxyz** [tom-bell/bearing#13]
Calling cancel on a LocationTask object does not cancel the underlying Google location service. This appears to be because taskId is never set by subclasses and so is always null. 

I believe for PeriodicLocationTask it should be set to the result of locationProvider.requestRecurringLocationUpdates? 

Cheers

**Comment by scruffyfox** [comment]
+1

**Comment by tom-bell** [comment]
Nice catch, thanks. Will provide a fix in the next few days.
